# Generated by Django 6.0.1 on 2026-02-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_content_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='isRead',
        ),
    ]
