# Generated by Django 6.0.1 on 2026-02-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_is_read_message_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isRead',
            new_name='is_read',
        ),
    ]
