# Generated by Django 6.0.1 on 2026-02-03 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('email', 'Mail Verification'), ('password', 'Password Reset Verification')], max_length=50)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('isVerifiedByUser', models.BooleanField(default=False)),
                ('expiryDateTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
