# Generated by Django 6.0.1 on 2026-02-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='token',
        ),
    ]
