# Generated by Django 6.0.1 on 2026-02-04 13:27

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userverification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='defaults/user-avatar.svg', upload_to=apps.users.models.profile_upload_path),
        ),
    ]
