# Generated by Django 6.0.1 on 2026-02-05 07:29

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('business_name', models.CharField(help_text='Brand name or Company name', max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=apps.users.models.bizz_profile_upload_path)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Only admin approved services are visible to all.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_services', to='users.sellerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='users.service'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('website', 'Personal Website')], max_length=20)),
                ('url', models.URLField(help_text='Full URL (e.g., https://github.com/username)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.sellerprofile')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
