# Generated by Django 6.0.1 on 2026-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sellerprofile_service_sellerprofile_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_verified',
            field=models.BooleanField(default=False),
        ),
    ]
