# Generated by Django 6.0.1 on 2026-02-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_main_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_main_verified',
            new_name='is_mail_verified',
        ),
    ]
