# Generated by Django 6.0.1 on 2026-02-05 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_is_main_verified_user_is_mail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
