# Generated by Django 6.0.1 on 2026-02-05 15:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sellerprofile_updated_at_alter_sellerprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/seller-avatar.svg', null=True, upload_to=apps.users.models.bizz_profile_upload_path),
        ),
    ]
