# Generated by Django 6.0.1 on 2026-02-12 08:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.blog_cover_upload_path),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='No Summary', max_length=200),
            preserve_default=False,
        ),
    ]
