# Generated by Django 6.0.1 on 2026-02-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastSeen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
