# Generated by Django 6.0.1 on 2026-02-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_isonline_user_lastseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isOnline',
            new_name='is_online',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastSeen',
            new_name='last_seen',
        ),
    ]
